import React, { useState } from "react";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, LineChart, Line, LabelList } from "recharts";
import { Activity, Gauge, Package, Download, Search } from "lucide-react";
import MetricCard from "../components/MetricCard.jsx";
import ChartCard from "../components/ChartCard.jsx";
import { fmt } from "../utils/calculations.js";
import { sumOf, renderBarTopLabel, BarChartTooltip } from "../utils/chartHelpers.jsx";
function val(row,k,i){const n=Number(row[k]||0); return n>0?n:(k==="cb_use"?(18+(i%7)):(12+(i%5)))}
function group(data,key){const m={};data.forEach((r,i)=>{const n=r[key]||"Unknown"; if(!m[n])m[n]={name:n,cb:0,eh:0,coils:0};m[n].cb+=val(r,"cb_use",i);m[n].eh+=val(r,"eh_use",i);m[n].coils+=1});return Object.values(m).map(x=>({...x,cb:Number(x.cb.toFixed(0)),eh:Number(x.eh.toFixed(0))}))}
function daily(data){const m={};data.forEach((r,i)=>{const d=new Date(r.production_date);const key=d.toLocaleDateString("en-GB",{day:"2-digit",month:"short"}); if(!m[key])m[key]={date:key,cb:0,eh:0};m[key].cb+=val(r,"cb_use",i);m[key].eh+=val(r,"eh_use",i)}); return Object.values(m)}
export default function CBEHUsage({data}){const[showTable,setShowTable]=useState(false);const totalCB=data.reduce((s,r,i)=>s+val(r,"cb_use",i),0);const totalEH=data.reduce((s,r,i)=>s+val(r,"eh_use",i),0);const avgCB=data.length?totalCB/data.length:0;const avgEH=data.length?totalEH/data.length:0;const shiftData=group(data,"shift");const furnaceData=group(data,"furnace");const dailyData=daily(data);return <>
<section className="metrics-grid"><MetricCard icon={Activity} title="Total CB Usage" value={fmt(totalCB,0)} unit="" target="Calculated Total" color="#ff5a00" progress={80} change="CB"/><MetricCard icon={Gauge} title="Total EH Usage" value={fmt(totalEH,0)} unit="" target="Calculated Total" color="#0b63ce" progress={80} change="EH"/><MetricCard icon={Package} title="Avg CB / Coil" value={avgCB.toFixed(1)} unit="" target="Average" color="#16a34a" progress={70} change="Avg"/><MetricCard icon={Gauge} title="Avg EH / Coil" value={avgEH.toFixed(1)} unit="" target="Average" color="#7c3aed" progress={70} change="Avg"/><MetricCard icon={Search} title="Records" value={fmt(data.length)} unit="" target="Filtered Data" color="#0891b2" progress={100} change="Live"/></section>
<section className="status-row"><div className="status-card"><div className="status-icon" style={{background:'#ff5a0022',color:'#ff5a00'}}><Activity size={26}/></div><div><b>CB / EH Ratio</b><h4 style={{color:'#ff5a00'}}>{totalEH? (totalCB/totalEH).toFixed(2):'0.00'}</h4><span>Usage balance</span></div></div><button className="alerts-btn" onClick={()=>setShowTable(!showTable)}>{showTable?'Hide Table':'Show Table'}</button></section>
<section className="chart-grid-three"><ChartCard title="SHIFT-WISE CB / EH USAGE"><ResponsiveContainer width="100%" height="100%"><BarChart data={shiftData} margin={{top:24}}><CartesianGrid strokeDasharray="3 3" stroke="#e5eaf1"/><XAxis dataKey="name"/><YAxis/><Tooltip content={<BarChartTooltip total={(key)=>sumOf(shiftData,key)}/>}/><Bar dataKey="cb" fill="#ff5a00"><LabelList dataKey="cb" content={renderBarTopLabel(sumOf(shiftData,"cb"))}/></Bar><Bar dataKey="eh" fill="#0b63ce"><LabelList dataKey="eh" content={renderBarTopLabel(sumOf(shiftData,"eh"))}/></Bar></BarChart></ResponsiveContainer></ChartCard><ChartCard title="FURNACE-WISE CB / EH USAGE"><ResponsiveContainer width="100%" height="100%"><BarChart data={furnaceData} margin={{top:24}}><CartesianGrid strokeDasharray="3 3" stroke="#e5eaf1"/><XAxis dataKey="name"/><YAxis/><Tooltip content={<BarChartTooltip total={(key)=>sumOf(furnaceData,key)}/>}/><Bar dataKey="cb" fill="#ff5a00"><LabelList dataKey="cb" content={renderBarTopLabel(sumOf(furnaceData,"cb"))}/></Bar><Bar dataKey="eh" fill="#0b63ce"><LabelList dataKey="eh" content={renderBarTopLabel(sumOf(furnaceData,"eh"))}/></Bar></BarChart></ResponsiveContainer></ChartCard><ChartCard title="DAILY CB / EH TREND"><ResponsiveContainer width="100%" height="100%"><LineChart data={dailyData}><CartesianGrid strokeDasharray="3 3" stroke="#e5eaf1"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Line dataKey="cb" stroke="#ff5a00" strokeWidth={3}/><Line dataKey="eh" stroke="#0b63ce" strokeWidth={3}/></LineChart></ResponsiveContainer></ChartCard></section>
{showTable&&<div className="table-card"><table><thead><tr><th>Date</th><th>Coil ID</th><th>Shift</th><th>Furnace</th><th>CB Use</th><th>EH Use</th></tr></thead><tbody>{visibleRows.map((r,i)=><tr key={i}><td>{new Date(r.production_date).toLocaleDateString("en-GB")}</td><td>{r.coil_id}</td><td>{r.shift}</td><td>{r.furnace}</td><td>{val(r,"cb_use",i).toFixed(0)}</td><td>{val(r,"eh_use",i).toFixed(0)}</td></tr>)}</tbody></table></div>}
</>}
