import React, { useMemo, useState } from "react";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, PieChart, Pie, Cell, Legend, LabelList } from "recharts";
import { Clock, AlertTriangle, Download, RefreshCcw, Search } from "lucide-react";
import MetricCard from "../components/MetricCard.jsx";
import ChartCard from "../components/ChartCard.jsx";
import { fmt } from "../utils/calculations.js";
import { sumOf, renderBarTopLabel, BarChartTooltip, PieChartTooltip } from "../utils/chartHelpers.jsx";
const COLORS = ["#ff5a00", "#0b63ce", "#16a34a", "#7c3aed", "#ef4444"];
function csv(rows){const h=["production_date","coil_id","shift","furnace","steel_grade_code","steel_grade_family","delay_minutes","status"];const text=[h.join(","),...rows.map(r=>h.map(k=>`"${String(k==="production_date"?new Date(r[k]).toLocaleDateString("en-GB"):r[k]??"").replace(/"/g,'""')}"`).join(","))].join("\n");const u=URL.createObjectURL(new Blob([text]));const a=document.createElement("a");a.href=u;a.download="delay_list.csv";a.click();URL.revokeObjectURL(u)}
function group(rows, key){const m={}; rows.forEach(r=>{const name=r[key]||"Unknown"; m[name]=(m[name]||0)+Number(r.delay_minutes||0)}); return Object.entries(m).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)}
export default function DelayList({ data }){
 const [search,setSearch]=useState(""); const [showTable,setShowTable]=useState(true);
 const delays=useMemo(()=>data.filter(r=>Number(r.delay_minutes||0)>0).filter(r=>!search||[r.coil_id,r.furnace,r.shift,r.steel_grade_code,r.steel_grade_family].some(v=>String(v||"").toLowerCase().includes(search.toLowerCase()))),[data,search]);
 const totalDelay=delays.reduce((s,r)=>s+Number(r.delay_minutes||0),0); const maxDelay=delays.length?Math.max(...delays.map(r=>Number(r.delay_minutes||0))):0; const avgDelay=delays.length?totalDelay/delays.length:0; const furnaceData=group(delays,"furnace"); const shiftData=group(delays,"shift");
 return <>
  <section className="metrics-grid"><MetricCard icon={AlertTriangle} title="Delay Records" value={fmt(delays.length)} unit="" target="Rows with delay" color="#ef4444" progress={70} change="Alert" negative/><MetricCard icon={Clock} title="Total Delay" value={fmt(totalDelay,0)} unit="min" target="Filtered Delay" color="#ff5a00" progress={80} change="Min"/><MetricCard icon={Clock} title="Avg Delay" value={avgDelay.toFixed(1)} unit="min" target="Per delayed coil" color="#0b63ce" progress={65} change="Avg"/><MetricCard icon={AlertTriangle} title="Max Delay" value={fmt(maxDelay,0)} unit="min" target="Highest Delay" color="#7c3aed" progress={60} change="Max" negative/><MetricCard icon={Download} title="Dataset" value={fmt(data.length)} unit="Rows" target="Total Data" color="#16a34a" progress={100} change="All"/></section>
  <section className="data-toolbar card"><div className="toolbar-left"><div className="search-input"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search delay coil, furnace, shift, grade..."/></div></div><div className="toolbar-right"><button className="secondary-btn" onClick={()=>setShowTable(!showTable)}>{showTable?"Hide Table":"Show Table"}</button><button className="primary-btn" onClick={()=>csv(delays)}><Download size={15}/> Export CSV</button></div></section>
  <section className="chart-grid-three"><ChartCard title="FURNACE-WISE DELAY MINUTES"><ResponsiveContainer width="100%" height="100%"><BarChart data={furnaceData} margin={{top:24}}><CartesianGrid strokeDasharray="3 3" stroke="#e5eaf1"/><XAxis dataKey="name"/><YAxis/><Tooltip content={<BarChartTooltip total={sumOf(furnaceData,"value")} unit="min"/>}/><Bar dataKey="value" fill="#ff5a00" radius={[6,6,0,0]}><LabelList dataKey="value" content={renderBarTopLabel(sumOf(furnaceData,"value"))}/></Bar></BarChart></ResponsiveContainer></ChartCard><ChartCard title="SHIFT-WISE DELAY MINUTES"><ResponsiveContainer width="100%" height="100%"><BarChart data={shiftData} margin={{top:24}}><CartesianGrid strokeDasharray="3 3" stroke="#e5eaf1"/><XAxis dataKey="name"/><YAxis/><Tooltip content={<BarChartTooltip total={sumOf(shiftData,"value")} unit="min"/>}/><Bar dataKey="value" fill="#0b63ce" radius={[6,6,0,0]}><LabelList dataKey="value" content={renderBarTopLabel(sumOf(shiftData,"value"))}/></Bar></BarChart></ResponsiveContainer></ChartCard><ChartCard title="DELAY SHARE BY FURNACE"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={furnaceData} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90} label={false} labelLine={false}>{furnaceData.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip content={<PieChartTooltip total={sumOf(furnaceData,"value")} unit="min"/>}/><Legend/></PieChart></ResponsiveContainer></ChartCard></section>
  {showTable&&<div className="table-card"><table><thead><tr><th>Date</th><th>Coil ID</th><th>Shift</th><th>Furnace</th><th>Grade</th><th>SGF</th><th>Delay Min</th><th>Status</th></tr></thead><tbody>{delays.map((r,i)=><tr key={i}><td>{new Date(r.production_date).toLocaleDateString("en-GB")}</td><td>{r.coil_id}</td><td>{r.shift}</td><td>{r.furnace}</td><td>{r.steel_grade_code}</td><td>{r.steel_grade_family}</td><td>{r.delay_minutes}</td><td>{r.status}</td></tr>)}</tbody></table></div>}
 </>;
}
