import React, { useState } from "react";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, PieChart, Pie, Cell, Legend, LabelList } from "recharts";
import { Clock, Package, Gauge, XCircle, BarChart3 } from "lucide-react";
import MetricCard from "../components/MetricCard.jsx";
import ChartCard from "../components/ChartCard.jsx";
import { fmt, percent } from "../utils/calculations.js";
import { sumOf, renderBarTopLabel, BarChartTooltip, PieChartTooltip } from "../utils/chartHelpers.jsx";
const COLORS=["#ff5a00","#0b63ce","#16a34a","#7c3aed"];
function summary(data){return ["A","B","C"].map(shift=>{const rows=data.filter(r=>r.shift===shift);const tonnage=rows.reduce((s,r)=>s+Number(r.weight||0),0);const rejects=rows.filter(r=>String(r.status).toUpperCase()==="FAIL").length;const delay=rows.reduce((s,r)=>s+Number(r.delay_minutes||0),0);const y=rows.length?rows.reduce((s,r)=>s+Number(r.yield_percent||0),0)/rows.length:0;return{shift:`Shift ${shift}`,raw:shift,coils:rows.length,tonnage:Number(tonnage.toFixed(0)),avgYield:Number(y.toFixed(2)),rejects,delay,rejectionRate:rows.length?Number((rejects/rows.length*100).toFixed(2)):0}})}
export default function ShiftInformation({data}){const[showTable,setShowTable]=useState(false);const rows=summary(data);const best=[...rows].sort((a,b)=>b.tonnage-a.tonnage)[0]||{};const totalTonnage=data.reduce((s,r)=>s+Number(r.weight||0),0);const rejects=data.filter(r=>String(r.status).toUpperCase()==="FAIL").length;const totalDelay=data.reduce((s,r)=>s+Number(r.delay_minutes||0),0);const avgYield=data.length?data.reduce((s,r)=>s+Number(r.yield_percent||0),0)/data.length:0;return <>
<section className="metrics-grid"><MetricCard icon={Clock} title="Active Shifts" value={rows.filter(r=>r.coils>0).length} unit="" target="A / B / C" color="#ff5a00" progress={90} change="Live"/><MetricCard icon={Package} title="Total Coils" value={fmt(data.length)} unit="Coils" target="Filtered Data" color="#0b63ce" progress={92} change="Live"/><MetricCard icon={BarChart3} title="Total Tonnage" value={fmt(totalTonnage,0)} unit="MT" target="Shift Output" color="#16a34a" progress={88} change="MT"/><MetricCard icon={Gauge} title="Avg Yield" value={avgYield.toFixed(2)} unit="%" target="All Shifts" color="#7c3aed" progress={85} change="Avg"/><MetricCard icon={XCircle} title="Rejects" value={fmt(rejects)} unit="" target={`${percent(rejects,data.length)}% of Total`} color="#ef4444" progress={45} change="Monitor" negative/></section>
<section className="status-row"><div className="status-card"><div className="status-icon" style={{background:'#ff5a0022',color:'#ff5a00'}}><Clock size={26}/></div><div><b>Best Shift</b><h4 style={{color:'#ff5a00'}}>{best.shift||'N/A'}</h4><span>{fmt(best.tonnage||0,0)} MT production</span></div></div><div className="status-card"><div className="status-icon" style={{background:'#0b63ce22',color:'#0b63ce'}}><Package size={26}/></div><div><b>Total Delay</b><h4 style={{color:'#0b63ce'}}>{fmt(totalDelay,0)} min</h4><span>All shift delays</span></div></div><button className="alerts-btn" onClick={()=>setShowTable(!showTable)}>{showTable?'Hide Table':'Show Table'}</button></section>
<section className="chart-grid-three"><ChartCard title="SHIFT-WISE TONNAGE"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} margin={{top:24}}><CartesianGrid strokeDasharray="3 3" stroke="#e5eaf1"/><XAxis dataKey="shift"/><YAxis/><Tooltip content={<BarChartTooltip total={sumOf(rows,"tonnage")} unit="MT"/>}/><Bar dataKey="tonnage" fill="#ff5a00" radius={[6,6,0,0]}><LabelList dataKey="tonnage" content={renderBarTopLabel(sumOf(rows,"tonnage"))}/></Bar></BarChart></ResponsiveContainer></ChartCard><ChartCard title="SHIFT-WISE COILS"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} margin={{top:24}}><CartesianGrid strokeDasharray="3 3" stroke="#e5eaf1"/><XAxis dataKey="shift"/><YAxis/><Tooltip content={<BarChartTooltip total={sumOf(rows,"coils")}/>}/><Bar dataKey="coils" fill="#0b63ce" radius={[6,6,0,0]}><LabelList dataKey="coils" content={renderBarTopLabel(sumOf(rows,"coils"))}/></Bar></BarChart></ResponsiveContainer></ChartCard><ChartCard title="SHIFT TONNAGE SHARE"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={rows} dataKey="tonnage" nameKey="shift" innerRadius={55} outerRadius={90} label={false} labelLine={false}>{rows.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip content={<PieChartTooltip total={sumOf(rows,"tonnage")} unit="MT"/>}/><Legend/></PieChart></ResponsiveContainer></ChartCard></section>
{showTable&&<div className="table-card"><table><thead><tr><th>Shift</th><th>Coils</th><th>Tonnage MT</th><th>Avg Yield %</th><th>Rejects</th><th>Delay Min</th><th>Rejection Rate %</th></tr></thead><tbody>{rows.map(r=><tr key={r.shift}><td>{r.shift}</td><td>{fmt(r.coils)}</td><td>{fmt(r.tonnage,0)}</td><td>{r.avgYield.toFixed(2)}</td><td>{fmt(r.rejects)}</td><td>{fmt(r.delay,0)}</td><td>{r.rejectionRate.toFixed(2)}</td></tr>)}</tbody></table></div>}
</>}
